# Fichier de configuration pour la base de données
# Ce fichier DOIT être versionné sur Git.
# Il sert de modèle pour le fichier secret.properties.

# URL de connexion JDBC pour la base de données Oracle
db.url='jdbc:oracle:thin:@charlemagne.iutnc.univ-lorraine.fr:1521:infodb'

# Nom d'utilisateur
db.user=''

# Mot de passe
db.password=''
