

# URL de connexion JDBC pour la base de données Oracle
db.url='jdbc:oracle:thin:@charlemagne.iutnc.univ-lorraine.fr:1521:infodb'

# Nom d'utilisateur
db.user='e54916u'

# Mot de passe
db.password='Oreo2017@'
