DROP TABLE  RMI_RESERVATION CASCADE CONSTRAINTS;
DROP TABLE  RMI_TABLE CASCADE CONSTRAINTS;
DROP TABLE   RMI_CLIENT CASCADE CONSTRAINTS;
DROP TABLE  RMI_RESTAURANTS CASCADE CONSTRAINTS;

CREATE TABLE RMI_RESTAURANTS(
    id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    nom VARCHAR2(255) NOT NULL,
    adresse VARCHAR2(255),
    coord VARCHAR2(255)
);

CREATE TABLE RMI_CLIENT(
    id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    nom VARCHAR2(255) NOT NULL,
    prenom VARCHAR2(255),
    numtel VARCHAR2(20)
);

CREATE TABLE RMI_TABLE(
    id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    idRes RAW(16) NOT NULL,
    numTable VARCHAR2(10),
    nbPlaces NUMBER NOT NULL,
    CONSTRAINT FK_TABLE_RESTAURANT FOREIGN KEY (idRes) REFERENCES RMI_RESTAURANTS(id) ON DELETE CASCADE
);

CREATE TABLE RMI_RESERVATION(
    id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    idCli RAW(16) NOT NULL,
    idTab RAW(16) NOT NULL,
    nbConvives NUMBER,
    dateReservation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_RESERVATION_CLIENT FOREIGN KEY (idCli) REFERENCES RMI_CLIENT(id) ON DELETE CASCADE,
    CONSTRAINT FK_RESERVATION_TABLE FOREIGN KEY (idTab) REFERENCES RMI_TABLE(id) ON DELETE CASCADE
);

INSERT INTO RMI_RESTAURANTS (nom, adresse, coord) VALUES ('Le Grenier à Sel', '28 Place de la Carrière, 54000 Nancy', '48.696614, 6.182247');
INSERT INTO RMI_RESTAURANTS (nom, adresse, coord) VALUES ('Excelsior', '50 Rue Henri Poincaré, 54000 Nancy', '48.690833, 6.176389');
INSERT INTO RMI_RESTAURANTS (nom, adresse, coord) VALUES ('Le Bouche à Oreille', '42 Rue des Carmes, 54000 Nancy', '48.691472, 6.181822');
INSERT INTO RMI_RESTAURANTS (nom, adresse, coord) VALUES ('La Table du Bon Roi Stanislas', '7 Rue Gustave Simon, 54000 Nancy', '48.693631, 6.181315');
INSERT INTO RMI_RESTAURANTS (nom, adresse, coord) VALUES ('Les Frères Marchand', '99 Grande Rue, 54000 Nancy', '48.695392, 6.179914');
INSERT INTO RMI_RESTAURANTS (nom, adresse, coord) VALUES ('RAYA', '1 Bd de l''Insurrection du Ghetto de Varsovie, 54000 Nancy','48.685558, 6.181652');
INSERT INTO RMI_RESTAURANTS (nom, adresse, coord) VALUES ('Chicken Street','16 Av. du Général Leclerc, 54000 Nancy','48.684414, 6.186244');

INSERT INTO RMI_TABLE (idRes, numTable, nbPlaces) VALUES ((SELECT id FROM RMI_RESTAURANTS WHERE nom = 'Le Grenier à Sel'), '1', 4);
INSERT INTO RMI_TABLE (idRes, numTable, nbPlaces) VALUES ((SELECT id FROM RMI_RESTAURANTS WHERE nom = 'Le Grenier à Sel'), '2', 6);
INSERT INTO RMI_TABLE (idRes, numTable, nbPlaces) VALUES ((SELECT id FROM RMI_RESTAURANTS WHERE nom = 'Le Grenier à Sel'),3,4);

INSERT INTO RMI_CLIENT(nom, prenom, numtel) VALUES ('admin','admin','0123456789');

GRANT SELECT, INSERT, UPDATE, DELETE ON RMI_RESTAURANTS TO SPATH2U, E65120U, E54916U, E85474U;
GRANT SELECT, INSERT, UPDATE, DELETE ON RMI_CLIENT TO SPATH2U, E65120U, E54916U, E85474U;
GRANT SELECT, INSERT, UPDATE, DELETE ON RMI_TABLE TO SPATH2U, E65120U, E54916U, E85474U;
GRANT SELECT, INSERT, UPDATE, DELETE ON RMI_RESERVATION TO SPATH2U, E65120U, E54916U, E85474U;

COMMIT;
